# Generated by Django 4.0.1 on 2022-02-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_artwork_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='owner',
        ),
    ]
